# Generated by Django 4.2.6 on 2023-12-09 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderhistory",
            old_name="blue",
            new_name="A",
        ),
        migrations.RenameField(
            model_name="orderhistory",
            old_name="green",
            new_name="B",
        ),
        migrations.RenameField(
            model_name="orderhistory",
            old_name="red",
            new_name="C",
        ),
        migrations.RenameField(
            model_name="orderhistory",
            old_name="yellow",
            new_name="D",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="blue",
            new_name="A",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="green",
            new_name="B",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="red",
            new_name="C",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="yellow",
            new_name="D",
        ),
    ]
