# Generated by Django 4.2.6 on 2023-12-12 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_blue_orderhistory_a_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
