# Generated by Django 4.2.6 on 2023-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_rename_v_orderhistory_f_rename_v_user_f_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="status",
            field=models.CharField(default="pending", max_length=100),
        ),
    ]
