# Generated by Django 4.2.6 on 2023-12-18 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_orderhistory_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderhistory",
            name="status",
        ),
    ]
