# Generated by Django 4.2.6 on 2024-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_orderhistory_h_remove_user_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='click_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
